accounts/urls.py
from django.urls import include, path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts.views import signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ExpenseCategoryListView,
    AccountListView,
    ReceiptListView,
    ReceiptCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# Create your models here.


# Expense Category model
class ExpenseCategory(models.Model):
    # name max length 50
    name = models.CharField(max_length=50)
    # an owner with foreign key to user
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        # related name of categories
        related_name="categories",
        # cascade delete
        on_delete=models.CASCADE,
    )

    # a __str__ method that returns name value
    def __str__(self):
        return self.name


# Account model
class Account(models.Model):
    # name max length 100
    name = models.CharField(max_length=100)
    # number that has chars with max 20
    number = models.CharField(max_length=20)
    # an owner with foreign key to user
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        # related name of accounts
        related_name="accounts",
        # cascade delete
        on_delete=models.CASCADE,
    )

    # a __str__ method that returns name value
    def __str__(self):
        return self.name


# Receipt model
class Receipt(models.Model):
    # vendor chars max length 200
    vendor = models.CharField(max_length=200)
    # total decimalFeild
    total = models.DecimalField(max_digits=10, decimal_places=3)
    # three decimal places
    # max 10 digits
    # tax decimalFeild
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    # three decimals
    # max 10 digits
    # date of when transaction tokk place
    date = models.DateTimeField()

    # purchaser with foreign ket to user
    purchaser = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        # a related name of receipts
        related_name="receipts",
        # cascade delete
        on_delete=models.CASCADE,
    )

    # category with foreign ket to ExpenseCategory model
    category = models.ForeignKey(
        "ExpenseCategory",
        # reletated name receipts
        related_name="receipts",
        # cascade delete
        on_delete=models.CASCADE,
    )

    # account with foreign key to Account model
    account = models.ForeignKey(
        "Account",
        # a related name to receipts
        related_name="receipts",
        # cascade delete
        on_delete=models.CASCADE,
        # alow to be null
        null=True,
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
# from django.shortcuts import redirect
from django.shortcuts import redirect
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
from receipts.models import (
    Receipt,
    ExpenseCategory,
    Account,
)


class ExpenseCategoryListView(ListView):
    model = ExpenseCategory
    template_name = "expense_categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

receipts/templates/accounts/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Me Receipts</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <h1>Account</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Number of receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for account in account_list %}
                <tr>
                    <td> {{account.name}} </td>
                    <td> {{account.number}} </td>
                    <td> {{account.receipt.all|length}} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>
</body>

</html>

receipts/templates/expense_categories/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Me Receipts</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <h1>Expense Categories</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of Receipts</th>
                </tr>
            <tbody>
                {% for category in expensecategory_list %}
                <tr>
                    <td> {{category.name}} </td>
                    <td> {{category.receipt.all|length}} </td>
                </tr>
                {% endfor %}
            </tbody>
            </thead>
        </table>
    </main>
</body>

</html>

receipts/templates/receipts/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Me Receipts</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/receipts/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Me Receipts</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Due Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for receipt in receipt_list %}
                    <td> {{receipt.vendor}} </td>
                    <td> {{receipt.total}} </td>
                    <td> {{receipt.tax}} </td>
                    <td> {{receipt.date|date:"m-d-Y" }} </td>
                    <td> {{receipt.category.name}} </td>
                    <td> {{receipt.account.name}} </td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </main>
</body>

</html>